# file: C:\Users\rudra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\jsonschema\exceptions.py
# hypothesis_version: 6.135.14

['$', '.', 'RefResolutionError', '[', ']', '_wrapped', 'anyOf', 'cause', 'context', 'error', 'errors', 'instance', 'message', 'metaschema', 'oneOf', 'parent', 'path', 'schema', 'schema_path', 'type', 'validator', 'validator_value']